# =============================================================================== #
# Neovide => Neovim Gui With Smooth Animation:                                    #
# =============================================================================== #
idle = true
tabs = true
vsync = true
title-hidden = true
no-multigrid = true
maximized = false
wsl = false
srgb = false
fork = false
frame = "none"
theme = "auto"
[font]
size = 10
hinting = "full"
edging = "antialias"
[[font.normal]]
family = "JetBrainsMono Nerd Font"
style = "W700"
[box-drawing]
mode = "font-glyph"
[box-drawing.sizes]
default = [1, 2]
